name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: eu-digital-green-certificates/dgca-app-core-ios
        ref: main
        path: dgca-app-core-ios
    - uses: actions/checkout@v2
      with:
        path: dgca-verifier-app-ios
    - name: debug
      run: |-
        ls -la .
    - name: xcode version
      run: |-
        ls /Applications | grep Xcode
        sudo xcode-select -switch /Applications/Xcode_12.4.app
        /usr/bin/xcodebuild -version
    - name: xcode test
      run: |-
        cd ./dgca-verifier-app-ios
        xcodebuild test \
        -scheme DGCAVerifier \
        -project DGCAVerifier.xcodeproj \
        -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' | xcpretty && exit ${PIPESTATUS[0]}

